export { scripts } from './tasks/scripts';
export { styles } from './tasks/styles';
export { fonts } from './tasks/fonts';
export { images } from './tasks/images';
export { svgs } from './tasks/svgs';
export { clean } from './tasks/clean';
export { monitor } from './tasks/monitor';
export { vendors } from './tasks/vendors';
export { templates } from './tasks/templates';
